version: "3.3"

services:
  # -- UI --
  ui:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: ui
    environment:
      - REACT_APP_API_URL_KU=https://portal.skillab-project.eu/ku-detection
      - REACT_APP_API_URL_KPI=https://portal.skillab-project.eu/policy
      - REACT_APP_API_URL_JBPM=https://portal.skillab-project.eu/jbpm/business-central/kie-wb.jsp
      - REACT_APP_API_URL_TRACKER=http://skillab-tracker.csd.auth.gr
      - REACT_APP_API_URL_LABOUR_DEMAND=https://portal.skillab-project.eu/labor-market-demand
      - REACT_APP_API_URL_SKILLS_REQUIRED=https://portal.skillab-project.eu/required-skills
      - REACT_APP_API_URL_SKILLS_DIVERSITY=https://portal.skillab-project.eu/diversity-analysis
      - REACT_APP_API_URL_SKILL_DEMAND_MATRIX=https://portal.skillab-project.eu/hcv
    ports:
      - '3000:3000'
    restart: unless-stopped


  # -- User management --
  user-management-backend:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: user-management-backend
    depends_on:
      - user-management-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-management-db:5432/test_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    ports:
      - '8086:8080'

  user-management-db:
    image: postgres:14.7
    container_name: user-management-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    restart: unless-stopped
    volumes:
       - user_management_postgresql_data:/var/lib/postgresql/data
  

  # -- Future Technology Trends Identifier --
  future-technology-trends-identifier:
    container_name: future-technology-trends-identifier
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    env_file:
      - .env
    volumes:  ## ToDo. Ask if its ok these volumes?
      - future_technology_trends_identifier_storage:/app/storage
      - future_technology_trends_identifier_datasets:/app/datasets
    ports:
      - "8876:8000"
    restart: unless-stopped


  # -- Policy Success Evaluator --
  policy-success-evaluator:  ## ToDo. Ask if this is ok
    container_name: policy-success-evaluator
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    env_file:
      - .env
    ports:
      - "8878:8000"
  

  # -- Employee Management --
  employee-management-app:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: employee-management-app
    depends_on:
      employee-management-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://employee-management-db:5432/test_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8888:8080"
    restart: unless-stopped
  
  employee-management-db:
    image: postgres:16-alpine
    container_name: employee-management-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - employee_management_postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  # -- Hiring Management --
  hiring-management-app:
    container_name: hiring-management-app
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    depends_on:
      hiring-management-db:
        condition: service_healthy
    ports:
      - "8890:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hiring-management-db:5432/hiringmanager_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    restart: unless-stopped

  hiring-management-db:
    image: postgres:16-alpine
    container_name: hiring-management-db
    environment:
      - POSTGRES_DB=hiringmanager_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - hiring_management_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hiringmanager_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  # -- KU Detection --
  ku-detection-backend:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: ku-detection-backend
    depends_on:
      - ku-detection-db
    environment:
      - DB_HOST=ku-detection-db
      - DB_PORT=5432
      - DB_NAME=test
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - '5000:5000'
    restart: unless-stopped

  ku-detection-db:
    image: postgres:16.2
    container_name: ku-detection-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - ku_detection_postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped


  #Organizational Skills Recommender?
  #digital-policy-management?



volumes:
  user_management_postgresql_data:
  future_technology_trends_identifier_storage:
  future_technology_trends_identifier_datasets:
  curriculum_skills_mysql:
  hierarchical_cumulative_voting_app:
  hiring_management_postgresql_data:
  employee_management_postgresql_data: